# Miyadaiku config file

# Base URL of the site
site_url: https://www.example.com

# Title of the site
site_title: Sample blog

# Default language code
lang: ja

# Default charset
charset: utf-8

# Default timezone
timezone: Asia/Tokyo

copyright: Copyright  © 2020 Miyadauku

#favicon: /static/newblog/img/favicon-32x32.png

# Default page description
#og_description: Sample new blog site
#
# Default page image file
#og_image: /static/newblog/img/logo.png
#
## site logo
#site_logo: /static/newblog/img/logo.png
#
## List of site theme
themes:
  - miyadaiku_theme_newblog

